getting-started: Add XMPP Providers and self-hosting possibility
xsf/xmpp.org pull request #1113
Opened 2022-03-24 20:22 UTC by melvo

2022-03-25 22:03 UTC, Echolon requested changes
I would simply reorder and put providers at the top.

2022-03-30 18:16 UTC, Echolon approved these changes

2022-03-30 18:16 UTC, Echolon commented
Deploy when website is ready.

2022-04-12 18:48 UTC, Echolon requested changes
Please lets only change the order

2022-04-22 08:53 UTC, Echolon approved these changes
Ok cool.

We can come back to this at a later stage. Im sure this will be the better path to go.

2022-04-22 08:53 UTC, Echolon commented
@wurstsalat3000 merge if you are happy

2022-04-22 10:15 UTC, wurstsalat3000 commented on content/getting-started.md
> +**XMPP Providers** combines different ratings and contains providers that are also in several uncurated lists.
```suggestion
**XMPP Providers** combines various ratings to compose a curated list. There are several other lists of providers in the web, which might not be curated.
```

2022-04-22 10:51 UTC, merged