German translation for July 2024 newsletter
xsf/xmpp.org pull request #1426
Opened 2024-08-30 17:10 UTC by Millesimus

Hey folks,

as I wrote in the communications MUC I translated the most recent newsletter to get a feeling for the task. Now I'm submitting my translation to familiarise myself with the workflow.

I'd be glad if you could confirm / deny if this is how you would like to receive the translations.  It's no problem if this PR comes too late to be actually merged.

2024-09-01 14:00 UTC, cal0pteryx requested changes
Thanks a lot! I left some suggestions. If you are ok with all of those, I would merge this PR.

Regarding XEP changelogs, we came to the conclusion that it does not really make sense to translate those, since they are for technical people anyway. So the changelog can be kept in its original form in the next newsletter issue.

I like the translation for various XEP processes though!

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +##  Meldungen der XSF
```suggestion
## Meldungen der XSF
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +Die XSF wurde auch 2024 wieder als [Gastgeber-Organisation im Google Summer of Code](https://wiki.xmpp.org/web/Google_Summer_of_Code_2024)! Folgende XMPP-Projekte haben Plätze erhalten und sind am co
```suggestion
Die XSF wurde auch 2024 wieder als [Gastgeber-Organisation im Google Summer of Code](https://wiki.xmpp.org/web/Google_Summer_of_Code_2024)! Folgende XMPP-Projekte haben Plätze erhalten und sind am Coden:
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +  - [Modernes Onboarding und Mediengallerie in Monal] (175 Arbeitsstunden, Medium)](https://wiki.xmpp.org/web/Gsoc2024/Monal/Media_Gallery)
```suggestion
  - [Modernes Onboarding und Mediengalerie in Monal] (175 Arbeitsstunden, Medium)](https://wiki.xmpp.org/web/Gsoc2024/Monal/Media_Gallery)
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +  - [Standard-konforme SMS-Authentifizierung via OTP compliant] (350 Arbeitsstunden, Medium)](https://wiki.xmpp.org/web/Gsoc2024/Prav.app/Standards_compliant_SMS_OTP_based_authentication)
```suggestion
  - [Standard-konforme SMS-Authentifizierung via OTP] (350 Arbeitsstunden, Medium)](https://wiki.xmpp.org/web/Gsoc2024/Prav.app/Standards_compliant_SMS_OTP_based_authentication)
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +Die XSF bietet XMPP-Projekten an, die [Verwaltung ihrer Finanzen](https://xmpp.org/community/fiscalhost/) zu übernehmen. Projekte können dies via via [Open Collective](https://opencollective.com/xmpp
```suggestion
Die XSF bietet XMPP-Projekten an, die [steuerliche Verwaltung ihrer Finanzen](https://xmpp.org/community/fiscalhost/) zu übernehmen. Projekte können dies via [Open Collective](https://opencollective.com/xmpp) anfragen. Für weitere Informationen, siehe [die ursprüngliche Ankündigung im Blog](https://xmpp.org/2021/09/the-xsf-as-a-fiscal-host/). Derzeit kann so an folgende Projekte gespendet werden:
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +- [Rivista](https://git.xmpp-it.net/sch/Rivista) ist ein neues Veröffentlichungssystem das aus XMPP PubSub-Knoten dynamisch eine Journal-Seite generiet. Rivista ist mit Atom/RSS kompatibel und kann a
```suggestion
- [Rivista](https://git.xmpp-it.net/sch/Rivista) ist ein neues Veröffentlichungssystem das aus XMPP PubSub-Knoten dynamisch eine Journal-Seite erstellt. Rivista ist mit Atom/RSS kompatibel und kann auch im Browser gelesen werden.
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +- [Ein Blogpost von Haiku-OS über den XMPP Sprint in Berlin im Juli 2024 (englisch)](https://www.haiku-os.org/blog/nephele/2024-07-21_xmpp_coding_sprint_berlin). Die [Liste der dort angegangenen Proj
```suggestion
- [Ein Blogpost von Haiku-OS über den XMPP Sprint in Berlin im Juli 2024 (englisch)](https://www.haiku-os.org/blog/nephele/2024-07-21_xmpp_coding_sprint_berlin). Die [Liste der dort bearbeiteten Projekte](https://wiki.xmpp.org/web/Sprints/2024-07_Berlin#Attendees) findet ihr im XMPP-Wiki.
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +- [JMP.chat-Newsletter Juli 2024: Anrufe aus SIP und ein möglicher neuer SMS-Tarif (englisch)](https://blog.jmp.chat/b/july-newsletter-2024)
```suggestion
- [JMP.chat-Newsletter Juli 2024: Anrufe aus SIP und ein möglicher neuer SIM-Tarif (englisch)](https://blog.jmp.chat/b/july-newsletter-2024)
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +- [Gajim 1.9.2](https://gajim.org/post/2024-07-19-gajim-1.9.2-released/) wurde veröffentlich. Die Änderungen umfasst eine wichtige Korrektur in der OMEMO-Verschlüsselung, native Benachrichtigungen un
```suggestion
- [Gajim 1.9.2](https://gajim.org/post/2024-07-19-gajim-1.9.2-released/) wurde veröffentlicht. Die Änderungen umfasst eine wichtige Korrektur in der OMEMO-Verschlüsselung, native Benachrichtigungen unter Windows und Verbesserungen in der Bedienung. Außerdem wurde [Gajim 1.9.3](https://gajim.org/post/2024-07-29-gajim-1.9.3-released/) mit einer Korrektur für den MS Store und weiteren Verbesserungen veröffentlicht.
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +- [Monal 6.4.1](https://github.com/monal-im/Monal/releases/tag/Build_iOS_941)wurde mit einigen Korrekturen und aktualisierten Übersetzungen veröffentlicht. ACHTUNG, das ist das letzte Release mit Unt
```suggestion
- [Monal 6.4.1](https://github.com/monal-im/Monal/releases/tag/Build_iOS_941) wurde mit einigen Korrekturen und aktualisierten Übersetzungen veröffentlicht. ACHTUNG, das ist das letzte Release mit Unterstützung für MacOS 11 und 12 sowie iOS 14 und 15. Außerdem wurde [Monal IM](https://monal-im.org/) von der [NGI der EU](https://ngi.eu) für [eine weitere Förderphase](https://nlnet.nl/project/Monal-IM-UI/) des [NLnet Foundation NGI0 Entrust Fund](https://nlnet.nl/entrust/) ausgewählt, um an einigen wichtigen Features zu arbeiten. Namentlich: die Implementierung eines Wählfelds, die Überarbeitung des UI-Codes, die Implementierung von Reaktionen, klickbaren Antworten und Stickern, Arbeiten im Rahmen der XSF und die Dokumentation von Monals Software-Architektur. Weitere Details im [Monal IM Blogpost (englisch)](https://monal-im.org/post/00013-nlnet-funding2/).
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +- [Movim 0.26](https://github.com/movim/movim/releases/tag/v0.26) wurde veröffentlicht. Neue Features sind benutzerdefinierte Emojis, Codeblöcke in Nachrichten, besseres Spam-Handling, bessere Nachri
```suggestion
- [Movim 0.26](https://github.com/movim/movim/releases/tag/v0.26) wurde veröffentlicht. Neue Features sind benutzerdefinierte Emojis, Codeblöcke in Nachrichten, besseres Spam-Handling, bessere Nachrichtenmoderation und -Rückzug und natürlich Fehlerkorrekturen.  Darüber hinaus wurde[Movim](http://movim.eu/) von der [NLnet Foundation](https://nlnet.nl/) für Förderungen aus dem [NGI0 Core](https://nlnet.nl/core/) ausgewählt, um an [vielen Features](https://mov.im/node/pubsub.movim.eu/Movim/f619c49c-ccd3-4487-8c2e-20b6d3555da2) rund um [Video-Konferenzen](https://nlnet.nl/project/Movim-E2EE-video/) zu arbeiten, unter Anderem Gruppenanrufe mit Audio und Video. Weitere Einblicke und technische Details folgen in künftigen Blogposts.
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +Beschrieben wird dieser XEP-Lebenszyklus samt förmlicher und kanonischer Definitionen der Typen, Zustände und Prozesse im ersten XEP, [XEP-0001](https://xmpp.org/extensions/xep-0001.html). [Lerne meh
```suggestion
Beschrieben wird dieser XEP-Lebenszyklus samt förmlicher und kanonischer Definitionen der Typen, Zustände und Prozesse im ersten XEP, [XEP-0001](https://xmpp.org/extensions/xep-0001.html). [Lerne mehr über den Standardisierungsprozess](https://xmpp.org/about/standards-process.html).
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +Letzte Aufrufe (_Last Calls_) erfolgen sobald sich der Status eines XEPs konsolidiert hat. Heißt: Nachdem der Rat einen XEP für fertig befunden hat, startet die:er XEP-Editor:in einen letzten Aufruf
```suggestion
Letzte Aufrufe (_Last Calls_) erfolgen sobald sich der Status eines XEPs konsolidiert hat. Heißt: Nachdem der Rat einen XEP für fertig befunden hat, startet die:er XEP-Editor:in einen letzten Aufruf für Kommentare. Die so erhaltenen Rückmeldungen helfen, den XEP zu verbessern. Danach geht er zurück an den Rat, um als _Stable_ eingestuft zu werden.
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +Auf der Suche nach Jobangeboten im XMPP-Umfeld oder professionellem Consulting für ein XMPP-Projekt? Wirf einen Blick auf unser  [job board](https://xmpp.work/)!
```suggestion
Auf der Suche nach Jobangeboten im XMPP-Umfeld oder professionellem Consulting für ein XMPP-Projekt? Wirf einen Blick auf unser [job board](https://xmpp.work/)!
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +Der XMPP-Newsletter wird gemeinsam von der XMPP-Gemeinschaft geschrieben. Die monatlich erscheinende Ausgabe wird in einem [schlichten Pad](https://pad.nixnet.services/oHnY_ZvLT8SoFyCqIC2ung) vorbere
```suggestion
Der XMPP-Newsletter wird gemeinsam von der XMPP-Gemeinschaft geschrieben. Die monatlich erscheinende Ausgabe wird in einem [schlichten Pad](https://pad.nixnet.services/oHnY_ZvLT8SoFyCqIC2ung) vorbereitet und am Ende des Monats in das [Github-Repositorium der XSF](https://github.com/xsf/xmpp.org) übertragen. Mach gerne mit! Komm in [unseren Chatraum (MUC)](xmpp:commteam@muc.xmpp.org?join) und hilf uns dabei, dieses Projekt fortzuführen. Hast Du ein neues Projekt, von dem Leute wissen sollten? Teile es in unserem Newsletter mit einem großen Publikum!
```

2024-09-01 14:00 UTC, cal0pteryx commented on content/blog/newsletter/2024-08-05-newsletter.de.md
> +Dieser Newsletter wird unter der  [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) veröffentlicht.
```suggestion
Dieser Newsletter wird unter der [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) veröffentlicht.
```

2024-09-03 18:36 UTC, Millesimus commented
Hey @cal0pteryx, thank you very much for your thorough and laborious review! I committed all your changes (though I realised too late that I wasn't adding them to the batch).

2024-09-03 19:47 UTC, merged

2024-09-03 19:48 UTC, cal0pteryx commented
Thanks! :)