German translation for August 2024 newsletter
xsf/xmpp.org pull request #1428
Opened 2024-09-04 19:15 UTC by Millesimus

Hey folks,

with this PR I hand in the / my translation for #1427. 

Two remarks:

1. "Blasta" is described as an annotation system (when linking to its introduction video) but later on as a bookmarking system. I think the latter would be easier to understand than "Annotationssystem" which is why I translated it as "Lesezeichensystem", in both cases.
2. As [requested](https://github.com/xsf/xmpp.org/pull/1426#pullrequestreview-2274384419) I didn't translate the XEP log in detail, but I translated all the boilerplate texts which I just had to copypaste from last months issue.

2024-09-06 21:44 UTC, Echolon requested changes

2024-09-06 21:44 UTC, Echolon commented on content/blog/newsletter/2024-09-05-newsletter.de.md
> +
Ich glaube hier fehlen noch die Wahlen

2024-09-06 21:44 UTC, Echolon commented on content/blog/newsletter/2024-09-05-newsletter.de.md
> -
Hattest du die Yuno änderung integriert? evtl. nochmal meine editorials und den letzten PR von gnemmi der bereits gemerged ist checken.

Generell empfehlen ich auch gerne noch etwas zu warten damit die iterationen weniger sind und du weniger arbeit hast. Kommt nicht auf den Tag an bei unseren Resourcen.

2024-09-07 20:45 UTC, Millesimus commented on content/blog/newsletter/2024-09-05-newsletter.de.md
> -
Yunohost bzw. das Package ist drin, ja.

2024-09-09 19:54 UTC, merged

2024-09-09 19:54 UTC, cal0pteryx commented
Thanks a lot!