Create 2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
xsf/xmpp.org pull request #874
Opened 2021-01-22 18:28 UTC by Echolon

Hello,

I started the German translation for https://github.com/xsf/xmpp.org/pull/871

Please focus to the translation.
Bitte fokussiert euch auf die Übersetzung.

2021-01-22 18:30 UTC, Echolon commented
FYI @wurstsalat3000 @mdosch @vanitasvitae @ge0rg

2021-01-23 18:34 UTC, wurstsalat3000 commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +_Dies ist die deutsche Übersetzung dieses ursprünglichen Blogeintrag._
[...] des ursprünglichen Blogeintrags.

2021-01-23 18:34 UTC, wurstsalat3000 commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +Viele fügen sogar einen weiteren Messenger zu ihrer immer größer werdenden Sammlung von Messengern hinzu, was wahrscheinlich eher frustrierend als hilfreich ist. Das bringt mich zurück zur ursprüngli
[...] zur ursprünglichen Fragestellung: Welches Problem will man hier lösen?

2021-01-23 18:34 UTC, wurstsalat3000 commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +Unterschiedliche Menschen haben unterschiedliche Überlegungen zur Beantwortung dieser Frage - manche benötigen einen effektiven Datenschutz, oder Datenhoheit, oder einfach die Möglichkeit, alle ihre
Verschiedene Menschen haben unterschiedliche Überlegungen [...]

2021-01-23 18:34 UTC, wurstsalat3000 commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +Wie Sie vielleicht schon vermutet haben, werde ich für XMPP plädieren. Ich denke, die erste Wahl, die man treffen sollte, ist nicht, welchen Messenger man verwendet, sondern welche zugrundeliegende S
Ich denke, die erste zu treffende Entscheidung sollte nicht sein, welchen Messenger man verwendet, [...]

2021-01-23 18:34 UTC, wurstsalat3000 commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +Im Gegensatz zur aktuellen Situation, in der andere Ihnen ihren bevorzugten Messenger vorschlagen, haben Sie im XMPP-Universum die freie Wahl unter vielen Messengern - suchen Sie sich den aus, der Ih
freie Wahl aus vielen Messengern

2021-01-23 18:34 UTC, wurstsalat3000 commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +in einer großen Anzahl von Software eingesetzt wird. Wir denken, dass dies eine gute Lösung für die meisten Menschen und Organisationen da draußen und das Internet als Ganzes ist - und es ist offen f
[...] weltweit in einer Vielzahl von Anwendungen eingesetzt wird.

2021-01-23 18:34 UTC, wurstsalat3000 commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +in einer großen Anzahl von Software eingesetzt wird. Wir denken, dass dies eine gute Lösung für die meisten Menschen und Organisationen da draußen und das Internet als Ganzes ist - und es ist offen f
Wir sind der Meinung, dass dies eine gute Lösung für die meisten Menschen und Organisationen da draußen sowie das Internet als Ganzes sein kann [...]

2021-01-24 21:34 UTC, Echolon commented
Thank you very much again for you help @wurstsalat3000 !

2021-01-25 15:59 UTC, mdosch commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +Ich fragte mich, wie ich dies beantworten sollte. Natürlich hätte ich einfach für XMPP (Extensible Messaging and Presence Protocol) plädieren können, aber dann dachte ich, dass dies allein vielleicht
Evtl. "und so werden sie wahrscheinlich später…"

2021-01-25 16:00 UTC, mdosch commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +die den Hype vermeidet und bei der man nicht mehrere Messenger-Apps installieren muss?
Welcher hype ist gemeint? Vielleicht eher "die Hype vermeidet" statt "die _den_ Hype vermeidet"?

2021-01-25 16:01 UTC, mdosch commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +Verschiedene Menschen haben verschiedene Überlegungen zur Beantwortung dieser Frage - manche benötigen einen effektiven Datenschutz, oder Datenhoheit, oder einfach die Möglichkeit, alle ihre Kontakte
Vor Datenhoheit würde ich das "oder" rausnehmen.

2021-01-25 16:02 UTC, mdosch commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +> XMPP ist ein offenes Protokoll, so wie HTTP für das Web ist. Es spielt keine Rolle, wie Ihre Website aussieht, jeder kann mit ihr interagieren. Dieses Prinzip ist die Idee hinter XMPP, allerdings f
Ich würd "so wie es HTTP für das Web ist" schreiben. So klingt der Satz unvollständig.

2021-01-25 16:05 UTC, mdosch commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +bis zur nächsten Internet-Modeerscheinung. Der Unterschied ist, dass Sie unabhängig davon, welche Messaging-App Sie verwenden oder welche App Ihre Freunde benutzen, immer noch den Komfort haben, mit
Der Satz klingt komisch. Ich würde etwas umformulieren. Z.B. "Im Gegensatz zur aktuellen Situation, in der andere Ihnen ihren bevorzugten Messenger vorschlagen, haben Sie im XMPP-Universum die freie Wahl aus vielen Messengern - suchen Sie sich den aus, der Ihnen gefällt, nicht den, den andere mögen und der bei der nächsten Internet-Modeerscheinung wieder ausgetauscht wird."

2021-01-25 16:06 UTC, mdosch commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +in einer Vielzahl von Anwendungen eingesetzt wird. Wir sind der Meinung, dass dies eine gute Lösung für die meisten Menschen und Organisationen da draußen sowie das Internet als Ganzes sein kann - un
"eingesetzt werden".

2021-01-25 16:06 UTC, mdosch commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +in einer Vielzahl von Anwendungen eingesetzt wird. Wir sind der Meinung, dass dies eine gute Lösung für die meisten Menschen und Organisationen da draußen sowie das Internet als Ganzes sein kann - un
"für die Zukunft zu ermöglichen"?

2021-01-25 16:14 UTC, vanitasvitae requested changes
My 15 cents ;)

2021-01-25 16:14 UTC, vanitasvitae commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +Bei der XMPP Standards Foundation und bei vielen anderen, die an dieser offenen Technologie beteiligt sind, sind wir der Meinung, dass XMPP als Kommunikationstechnologie eine gute Wahl ist, nicht nur
[...] gute Wahl ist, und das nicht nur in Hinblick auf Datenschutz.
[...] zwanzig Jahren und in dieser Zeit (Komma)
Dazu gehören viele Kriterien und Indikatoren, die sich als wertvoll für eine fundierte Wahl der Technologie und Ermöglichung von digitaler Souveränität herauskristalisiert haben. Dazu gehönren:

2021-01-25 16:14 UTC, vanitasvitae commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +- Innovation und den Einsatz offener Entwicklung
[...] und der Einsatz [...]

2021-01-25 16:14 UTC, vanitasvitae commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +> XMPP stellt definierte Informationen zur Verfügung, wie die Kommunikation in einem Netzwerk abgewickelt werden soll. Der Anwender entscheidet, welche Messaging-Software passt oder wo die Daten gesp
XMPP stellt eine Reihe von Spezifikatenen zur Verfügung, die definieren, wie die [...]
Der Anwender entscheidet, welche Software er nutzen möchte und wo [...]

2021-01-25 16:14 UTC, vanitasvitae commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +Im Gegensatz zur aktuellen Situation, in der andere Ihnen ihren bevorzugten Messenger vorschlagen, haben Sie im XMPP-Universum die freie Wahl aus vielen Messengern - suchen Sie sich den aus, der Ihne
Situation, in der jeder seinen bevorzugten Messenger vorschlägt, hat man im XMPP-Universum [...] Jeder kann den Messenger wählen der ihm gefällt, nicht den den andere einem vorgeben, bis dann die nächste Trend-App erscheint.

2021-01-25 16:14 UTC, vanitasvitae commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +bis zur nächsten Internet-Modeerscheinung. Der Unterschied ist, dass Sie unabhängig davon, welche Messaging-App Sie verwenden oder welche App Ihre Freunde benutzen, immer noch den Komfort haben, mit
Der Unterschied ist, dass man mit einem offenen Protokoll unabhängig von einzelnen Apps ist und trotzdem mit allen Kontakten im selben Netzwerk unterwegs sein kann, unabhängig von der Messengerwahl.

2021-01-25 16:14 UTC, vanitasvitae commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +Überlegen Sie sich, welche Technologie Sie einsetzen wollen, und entscheiden Sie dann, welcher Messenger zu Ihnen oder Ihrer Umgebung passt. XMPP und seine Community haben eine Vielzahl von Erfahrung
XMPP und seine Community kann auf eine große Menge an Erfahrung zurückgreifen, die erfolgreich in einer Vielzahl von Anwendungen umgesetzt werden.

2021-01-25 16:14 UTC, vanitasvitae commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +in einer Vielzahl von Anwendungen eingesetzt wird. Wir sind der Meinung, dass dies eine gute Lösung für die meisten Menschen und Organisationen da draußen sowie das Internet als Ganzes sein kann - un
[...] Innovation für die Zukunft zu schaffen.

2021-01-25 16:14 UTC, vanitasvitae commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +> XMPP hat nicht nur eine breite Palette an Messaging-Software, es gibt auch verschiedene Server-Software und Werkzeuge (Bibliotheken), um die Infrastruktur selbst aufzubauen.
[...] Server Systeme und Werkzeug (Bibliotheken und SDKs), die die Infrastruktur ausmachen.

2021-01-25 16:14 UTC, vanitasvitae commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +Es gibt nicht die eine Art, wie Kommunikations-Apps gestaltet werden müssen. Entscheiden Sie sich nachhaltig für eine standardisierte Technologie - dafür und für viele andere Zwecke empfehlen wir den
Kommunikationsanwendungen müssen nicht zentralisiert sein. Entscheidungen sollten nachhaltig getroffen werden und zugunsten von standardisierten Technologien getroffen werden - daher empfehlen wir für Instant Messaging und Echtzeitkommunikation den Einsatz von XMPP!

2021-01-25 19:30 UTC, Echolon commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +in einer Vielzahl von Anwendungen eingesetzt wird. Wir sind der Meinung, dass dies eine gute Lösung für die meisten Menschen und Organisationen da draußen sowie das Internet als Ganzes sein kann - un
Hmm, Einzahl "Erfahrung" oder?

2021-01-25 19:55 UTC, mdosch commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +in einer Vielzahl von Anwendungen eingesetzt wird. Wir sind der Meinung, dass dies eine gute Lösung für die meisten Menschen und Organisationen da draußen sowie das Internet als Ganzes sein kann - un
Ich würde "Erfahrungen" im Plural belassen und "eingesetzt werden" schreiben.

2021-01-25 20:01 UTC, Echolon reviewed
Thanks @mdosch and @vanitasvitae - quality quality quality!

Some formulations were too big that I refused to change. However, they were on point!

I am happy if you would like to point out your thoughts in an additional article, too! :yum:

2021-01-25 20:25 UTC, vanitasvitae commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +Kürzlich haben sich mehrere Leute bei mir gemeldet und gefragt, welche Art von Messenger sie jetzt verwenden sollten - sie sagten, dass ihnen nicht klar sein, worauf sie achten sollten und ob sie von
[...] nicht klar sei [...]

2021-01-25 21:44 UTC, Echolon commented on content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
> +in einer Vielzahl von Anwendungen eingesetzt wird. Wir sind der Meinung, dass dies eine gute Lösung für die meisten Menschen und Organisationen da draußen sowie das Internet als Ganzes sein kann - un
Ja, stimmt. Kognitive Dissonanz

2021-01-28 21:31 UTC, merged

2021-01-28 21:31 UTC, Echolon commented
Thanks to everyone helping!